service: fleapto-api

configValidationMode: errors
variablesResolutionMode: 20210326
useDotenv: true

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2
  profile: logan
  stage: dev
  lambdaHashingVersion: 20201221

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: fleapto-api-layer
      description: Fleapto REST API
      compatibleRuntimes:
        - python3.8

functions:
  app:
    package:
      patterns:
        - "app"
        - ".env"
        - "main.py"
        - "!requirements.txt"
        - "!package.json"
        - "!package-lock.json"
        - "!.serverless/**"
        - "!node_modules/**"

    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
